import * as u from './util.mjs'

export default [
  {
    id: 1,
    slug: `nick-woolsey`,
    title: `Nick Woolsey`,
    titleEn: ``,
    youtubeId: `a-eUAd7PzDc`,
    createdAt: null,
  },
  {
    id: 2,
    slug: `costa-rica-flow`,
    title: `Costa Rica Flow: Fire Poi in Paradise`,
    titleEn: ``,
    youtubeId: `OQJdmOhSsXU`,
    createdAt: null,
  },
  {
    id: 3,
    slug: `led-poi-yuta-2013`,
    title: `LED Poi Perfomance. Yuta Imamura. 2013`,
    titleEn: ``,
    youtubeId: `yQW3GZAh9Bg`,
    createdAt: null,
  },
  {
    id: 4,
    slug: `mel-led-poi`,
    title: `Mel. LED Poi`,
    titleEn: ``,
    youtubeId: `6sSwcpUbrtc`,
    createdAt: null,
  },
  {
    id: 5,
    slug: `led-light-poi-lighttoys-pyroterra`,
    title: `LED Light Poi — Lighttoys Pyroterra`,
    titleEn: ``,
    youtubeId: `TH-JE6alx1M`,
    createdAt: null,
  },
  {
    id: 6,
    slug: `asaf-mor-xmas`,
    title: `Asaf Mor — Xmas Poi`,
    titleEn: ``,
    youtubeId: `a7JwxvnxpW8`,
    createdAt: null,
  },
  {
    id: 7,
    slug: `fedor-sharapov-spb-showcase`,
    title: `Федор Шарапов, Санкт-Петербург, показательное выступление`,
    titleEn: ``,
    youtubeId: `aGya0tQKLps`,
    createdAt: null,
  },
  {
    id: 8,
    slug: `poiboy-physically-improbable`,
    title: `Poiboy — Physically Improbable`,
    titleEn: ``,
    youtubeId: `7uGuJAfdMVk`,
    createdAt: null,
  },
  {
    id: 9,
    slug: `fedor-sharapov-ivan-gorbunov-poi-duo`,
    title: `Fedor Sharapov & Ivan Gorbunov. POI DUO.`,
    titleEn: ``,
    youtubeId: `jT4-0Y_wEfg`,
    createdAt: null,
  },
  {
    id: 10,
    slug: `cyrille-humen-ejc-gala-show`,
    title: `Cyrille Humen fire Performance at the EJC fire Gala Show`,
    titleEn: ``,
    youtubeId: `Yfk-IsaXm2U`,
    createdAt: null,
  },
  {
    id: 11,
    slug: `living-lights-2013`,
    title: `Живые огни — Living Lights Festival 2013 — Anti-Spinners Poi Quartet`,
    titleEn: ``,
    youtubeId: `xb7kg9TBNVU`,
    createdAt: null,
  },
  {
    id: 12,
    slug: `spinning-in-silence`,
    title: `Thomas Johansson — Spinning in Silence`,
    titleEn: ``,
    youtubeId: `vMYhsB4Fj3E`,
    createdAt: null,
  },
  {
    id: 13,
    slug: `yuta-ronan-firedrums-2010`,
    title: `Yuta and Ronan Improvisation at Firedrums 2010`,
    titleEn: ``,
    youtubeId: `QTb61bj3MoI`,
    createdAt: null,
  },
  {
    id: 14,
    slug: `ronan-mcloughlin-universe-yours`,
    title: `Ronan McLoughlin — The Universe is Yours`,
    titleEn: ``,
    youtubeId: `cd724SgvyHs`,
    createdAt: null,
  },
  {
    id: 15,
    slug: `ben-drexler-dancing-promo`,
    title: `Ben Drexler — Drex Poi Dancing Promo`,
    titleEn: ``,
    youtubeId: `uL3e4TMvhAQ`,
    createdAt: null,
  },
  {
    id: 16,
    slug: `evgenii-pilipenko-2nd-siberia-festival`,
    title: `Евгений Пилипенко 2-е место, Сибирский Фестиваль Огня IV`,
    titleEn: ``,
    youtubeId: `aaC891h2LSc`,
    createdAt: null,
  },
  {
    id: 17,
    slug: `wafest-2014-ivan-gorbunov-showcase`,
    title: `WAFEst 2014 — Иван 'Мел' Горбунов (показательное)`,
    titleEn: ``,
    youtubeId: `E1QN9JZIG5U`,
    createdAt: null,
  },
  {
    id: 18,
    slug: `marvin-ong-fire-poi`,
    title: `Marvin Ong Fire Poi`,
    titleEn: ``,
    youtubeId: `ifj-uDY7Kbc`,
    createdAt: null,
  },
  {
    id: 19,
    slug: `noel-yee-flame-festival-2011`,
    title: `Noel Yee — Flame Festival 2011`,
    titleEn: ``,
    youtubeId: `G28k1jxIEUs`,
    createdAt: null,
  },
  {
    id: 20,
    slug: `yuta-nff-practice-2005`,
    title: `Yuta NFF Practice 2005`,
    titleEn: ``,
    youtubeId: `CpZgxSakQ98`,
    createdAt: null,
  },
  {
    id: 21,
    slug: `ronan-vojta-broken-toe-bros`,
    title: `Ronan and Vojta: Broken Toe Bros`,
    titleEn: ``,
    youtubeId: `oUWsrPaUMVE`,
    createdAt: null,
  },
  {
    id: 22,
    slug: `bliss-dance-nicky-evers-fire-poi`,
    title: `Bliss Dance — Nicky Evers Fire Poi`,
    titleEn: ``,
    youtubeId: `V8mS2IVEiRM`,
    createdAt: null,
  },
  {
    id: 23,
    slug: `loop-presents-loop-poi`,
    title: `LOOOOP presents LOOOOP POI`,
    titleEn: ``,
    youtubeId: `RPVfsRXUJdE`,
    createdAt: null,
  },
  {
    id: 24,
    slug: `fess-mrak-its-time`,
    title: `Fess & Mrak — It's Time [poi performance]`,
    titleEn: ``,
    youtubeId: `maf087bEWGU`,
    createdAt: null,
  },
  {
    id: 25,
    slug: `more-reasons-play-poi`,
    title: `More Reasons Go Play Poi with Friends!`,
    titleEn: ``,
    youtubeId: `vt6JT44kdig`,
    createdAt: null,
  },
  {
    id: 26,
    slug: `jonathan-alvarez-bending-light`,
    title: `Jonathan Alvarez — Bending Light`,
    titleEn: ``,
    youtubeId: `IZyfpn49zBQ`,
    createdAt: null,
  },
  {
    id: 27,
    slug: `tim-goddard-darwin-botanical-gardens`,
    title: `Tim Goddard — Darwin Botanical Gardens`,
    titleEn: ``,
    youtubeId: `qosgRYiDUjU`,
    createdAt: null,
  },
  {
    id: 28,
    slug: `dora-in-poi-leo-2015`,
    title: `d'ora in POI ... — Leo 2015`,
    titleEn: ``,
    youtubeId: `sfUQwSqXZZc`,
    createdAt: null,
  },
  {
    id: 29,
    slug: `lindzee-poi-bolas-poi-3-rhythms`,
    title: `Lindzee Poi: bolas, poi — 3 Rhythms`,
    titleEn: ``,
    youtubeId: `58fGEqTxDMQ`,
    createdAt: null,
  },
  {
    id: 30,
    slug: `vojta-stolbenko-around-the-world`,
    title: `Vojta Stolbenko — Around the world in a tea cup`,
    titleEn: ``,
    youtubeId: `CjL-ZQ8Kq40`,
    createdAt: null,
  },
  {
    id: 31,
    slug: `pois-shaking-the-world`,
    title: `Poi's Shaking the World!`,
    titleEn: ``,
    youtubeId: `HNcSCuy7aAY`,
    createdAt: null,
  },
  {
    id: 32,
    slug: `kerzhenets-2015-fess-poi`,
    title: `Kerzhenets 2015 (Fess poi)`,
    titleEn: ``,
    youtubeId: `IbDHJC0y5tY`,
    createdAt: null,
  },
  {
    id: 33,
    slug: `fedya-promo`,
    title: `Федор Шарапов — Показательное выступление`,
    titleEn: ``,
    youtubeId: `djICqxTbLys`,
    createdAt: `2015-08-08T11:03:28.888Z`,
  },
  {
    id: 34,
    slug: `partner_sk`,
    title: `Степан и Катя — Addicted Partner Poi `,
    titleEn: `Stefan & Kate — Addicted Partner Poi `,
    youtubeId: `fYmFja0mI2c`,
    createdAt: `2015-10-13T15:13:28.802Z`,
  },
  {
    id: 35,
    slug: `dolgy`,
    title: `Дмитрий Долгий — Firepoi`,
    titleEn: `Dmitry Dolgy — Firepoi`,
    youtubeId: `zUFIvUfFlDQ`,
    createdAt: `2015-10-20T20:48:00.091Z`,
  },
  {
    id: 36,
    slug: `ronancontact`,
    title: `Ronan McLoughlin — Poi`,
    titleEn: `Ronan McLoughlin — Poi`,
    youtubeId: `moX2a3g2NJU`,
    createdAt: `2016-05-12T16:13:14.354Z`,
  },
  {
    id: 37,
    slug: `poiboycontact`,
    title: `Poiboy — New poi routine`,
    titleEn: `Poiboy — New poi routine`,
    youtubeId: `PRvPpf-7SZ4`,
    createdAt: `2016-05-12T16:17:06.610Z`,
  },
  {
    id: 38,
    slug: `medi`,
    title: `Tim Goddard — MEDI`,
    titleEn: `Tim Goddard — MEDI`,
    youtubeId: `oVrtih_EgEQ`,
    createdAt: `2016-05-30T18:53:52.741Z`,
  },
  {
    id: 39,
    slug: `poiidd`,
    title: `Tim Goddard — POI IDD`,
    titleEn: `Tim Goddard — POI IDD`,
    youtubeId: `7dcXGpp7QMc`,
    createdAt: `2016-05-30T18:55:25.323Z`,
  },
  {
    id: 40,
    slug: `balanceandpoi`,
    title: `Fire and Crystal in the Desert by Edson Caballero`,
    titleEn: `Fire and Crystal in the Desert by Edson Caballero`,
    youtubeId: `pEJKTpj5yXc`,
    createdAt: `2016-06-08T20:24:40.411Z`,
  },
].sort(u.byPkDesc)
