import * as u from './util.mjs'

export default [
  {
    id: 1,
    slug: `spinning`,
    title: `Вращение пои`,
    titleEn: `Spin poi`,
    desc: ``,
    skillLevelId: 1,
  },
  {
    id: 3,
    slug: `butterfly`,
    title: `Бабочка`,
    titleEn: `Butterfly`,
    desc: ``,
    skillLevelId: 1,
  },
  {
    id: 4,
    slug: `weaves`,
    title: `Восьмерки`,
    titleEn: `Weaves`,
    desc: ``,
    skillLevelId: 1,
  },
  {
    id: 6,
    slug: `windmill`,
    title: `Мельница`,
    titleEn: `Windmill`,
    desc: ``,
    skillLevelId: 1,
  },
  {
    id: 7,
    slug: `wave`,
    title: `Волна`,
    titleEn: `Reels`,
    desc: ``,
    skillLevelId: 1,
  },
  {
    id: 8,
    slug: `saw`,
    title: `Пила`,
    titleEn: `Buzzsaw`,
    desc: ``,
    skillLevelId: 1,
  },
  {
    id: 9,
    slug: `exit`,
    title: `Раскрытия`,
    titleEn: `Lockouts`,
    desc: ``,
    skillLevelId: 1,
  },
  {
    id: 10,
    slug: `pendulums`,
    title: `Маятники`,
    titleEn: `Pendulums`,
    desc: ``,
    skillLevelId: 1,
  },
  {
    id: 11,
    slug: `stops`,
    title: `Остановки`,
    titleEn: `Stalls`,
    desc: ``,
    skillLevelId: 1,
  },
  {
    id: 12,
    slug: `fountain`,
    title: `Фонтан`,
    titleEn: `Fountain`,
    desc: ``,
    skillLevelId: 1,
  },
  {
    id: 13,
    slug: `corkscrew`,
    title: `Штопор`,
    titleEn: `Corkscrew`,
    desc: ``,
    skillLevelId: 1,
  },
  {
    id: 14,
    slug: `triple-behind`,
    title: `Движения за спиной`,
    titleEn: `Behind the Back`,
    desc: ``,
    skillLevelId: 2,
  },
  {
    id: 15,
    slug: `crosser`,
    title: `Кроссер`,
    titleEn: `Crosser`,
    desc: ``,
    skillLevelId: 2,
  },
  {
    id: 16,
    slug: `cosmo`,
    title: `Космо`,
    titleEn: `Cosmo`,
    desc: ``,
    skillLevelId: 2,
  },
  {
    id: 17,
    slug: `isolation`,
    title: `Изоляция`,
    titleEn: `Isolation`,
    desc: ``,
    skillLevelId: 2,
  },
  {
    id: 18,
    slug: `hooks`,
    title: `Зацепы и вействрапы`,
    titleEn: `Wraps & waistwraps`,
    desc: ``,
    skillLevelId: 2,
  },
  {
    id: 20,
    slug: `spiral`,
    title: `Спираль`,
    titleEn: `Spiral`,
    desc: ``,
    skillLevelId: 2,
  },
  {
    id: 21,
    slug: `underfoot`,
    title: `Движения под ногами`,
    titleEn: `Under the Leg`,
    desc: ``,
    skillLevelId: 2,
  },
  {
    id: 22,
    slug: `atomic`,
    title: `Атомик`,
    titleEn: `Atomic`,
    desc: ``,
    skillLevelId: 2,
  },
  {
    id: 23,
    slug: `hyperloop`,
    title: `Эйрврап и гиперлуп`,
    titleEn: `Hyperloop`,
    desc: ``,
    skillLevelId: 2,
  },
  {
    id: 25,
    slug: `flowers`,
    title: `Цветки`,
    titleEn: `Flowers`,
    desc: ``,
    skillLevelId: 2,
  },
  {
    id: 26,
    slug: `hybrids`,
    title: `Гибриды`,
    titleEn: `Hybrid`,
    desc: ``,
    skillLevelId: 3,
  },
  {
    id: 27,
    slug: `cateye`,
    title: `Кэтай`,
    titleEn: `Cateye`,
    desc: ``,
    skillLevelId: 3,
  },
  {
    id: 28,
    slug: `zans-diamond`,
    title: `Бриллиант Зана`,
    titleEn: `Zan's diamond`,
    desc: ``,
    skillLevelId: 3,
  },
  {
    id: 29,
    slug: `3d-moves`,
    title: `3D пои`,
    titleEn: `3D spinning`,
    desc: ``,
    skillLevelId: 3,
  },
  {
    id: 30,
    slug: `juggling`,
    title: `Броски пои`,
    titleEn: `Throws`,
    desc: ``,
    skillLevelId: 3,
  },
  {
    id: 31,
    slug: `contact`,
    title: `Контактные пои`,
    titleEn: `Contact poi`,
    desc: ``,
    skillLevelId: 3,
  },
  {
    id: 32,
    slug: `one-hand`,
    title: `Пои в одной руке`,
    titleEn: `One hand spinning`,
    desc: ``,
    skillLevelId: 3,
  },
  {
    id: 33,
    slug: `pro-poi`,
    title: `Три пои`,
    titleEn: `Three poi spinning`,
    desc: ``,
    skillLevelId: 3,
  },
  {
    id: 34,
    slug: `tricks`,
    title: `Трюки`,
    titleEn: `Trix`,
    desc: ``,
    skillLevelId: 3,
  },
  {
    id: 35,
    slug: `partner`,
    title: `Партнер — пои`,
    titleEn: `Partner poi`,
    desc: ``,
    skillLevelId: 3,
  },
  {
    id: 36,
    slug: `cap`,
    title: `Крыло`,
    titleEn: `CAP`,
    desc: ``,
    skillLevelId: 2,
  },
  {
    id: 37,
    slug: `tunnel`,
    title: `Тоннельные пои`,
    titleEn: `Tonnel poi`,
    desc: ``,
    skillLevelId: 3,
  },
].sort(u.byPkAsc)
