import * as u from './util.mjs'

export default [
  {
    id: 1,
    title: `Вращение пои вперед`,
    titleEn: `Spin forward`,
    desc: `Базовые принципы вращения пои вперед. Это самое начало начал на пути поинга. Место, с которого начинается отсчет в жизни каждого пойстера.`,
    rating: 1,
    elementId: 1,
    createdAt: null,
  },
  {
    id: 2,
    title: `Вращение пои назад`,
    titleEn: `Spin backward`,
    desc: `Базовые принципы вращения пои назад. Это самое начало начал на пути поинга. Место, с которого начинается отсчет в жизни каждого пойстера.`,
    rating: 1,
    elementId: 1,
    createdAt: null,
  },
  {
    id: 3,
    title: `Диагональ вперед`,
    titleEn: `Diagonal forward`,
    desc: `Основа для дальнейшего развития в поинге — это одновременное вращение пои по диагонали вперед.`,
    rating: 1,
    elementId: 1,
    createdAt: null,
  },
  {
    id: 4,
    title: `Диагональ назад`,
    titleEn: `Diagonal backward`,
    desc: `Основа для дальнейшего развития в поинге — это одновременное вращение пои по диагонали назад.`,
    rating: 1,
    elementId: 1,
    createdAt: null,
  },
  {
    id: 5,
    title: `Бабочка вперед`,
    titleEn: `Butterfly forward`,
    desc: ``,
    rating: 1,
    elementId: 3,
    createdAt: null,
  },
  {
    id: 6,
    title: `Бабочка назад`,
    titleEn: `Butterfly backward`,
    desc: ``,
    rating: 1,
    elementId: 3,
    createdAt: null,
  },
  {
    id: 8,
    title: `Двухбитка вперед`,
    titleEn: `2-beat weave forward`,
    desc: `Восьмерка представляет собой последовательное вращение двух пои c перекрещиванием рук.
Эта разновидность восьмерки называется двухбиткой вперед.
Название восьмерки зависит от количества прокрутов пои с каждой стороны.

Выполняя эти движения, важно сохранять ровные плоскости вращения пои слева и справа от себя. Обращайте особое внимание на движения кистей.`,
    rating: 1,
    elementId: 4,
    createdAt: null,
  },
  {
    id: 9,
    title: `Двухбитка назад`,
    titleEn: `2-beat weave backward`,
    desc: `Восьмерка представляет собой последовательное вращение двух пои c перекрещиванием рук.
Эта разновидность восьмерки называется двухбитка назад.
Название восьмерки зависит от количества прокрутов пои с каждой стороны.

Выполняя эти движения, важно сохранять ровные плоскости вращения пои слева и справа от себя. Обращайте особое внимание на движения кистей.`,
    rating: 1,
    elementId: 4,
    createdAt: null,
  },
  {
    id: 10,
    title: `Трехбитка вперед`,
    titleEn: `3-beat weave forward`,
    desc: `Восьмерка представляет собой последовательное вращение двух пои c перекрещиванием рук.
Эта разновидность восьмерки называется трехбитка вперед.
Название восьмерки зависит от количества прокрутов пои с каждой стороны.

Выполняя эти движения, важно сохранять ровные плоскости вращения пои слева и справа от себя. Обращайте особое внимание на движения кистей.`,
    rating: 1,
    elementId: 4,
    createdAt: null,
  },
  {
    id: 11,
    title: `Трехбитка назад`,
    titleEn: `3-beat weave backward`,
    desc: `Восьмерка представляет собой последовательное вращение двух пои c перекрещиванием рук.
Эта разновидность восьмерки называется трехбитка назад.
Название восьмерки зависит от количества прокрутов пои с каждой стороны.

Выполняя эти движения, важно сохранять ровные плоскости вращения пои слева и справа от себя. Обращайте особое внимание на движения кистей.`,
    rating: 1,
    elementId: 4,
    createdAt: null,
  },
  {
    id: 12,
    title: `Мельница`,
    titleEn: `Windmill`,
    desc: ``,
    rating: 1,
    elementId: 6,
    createdAt: null,
  },
  {
    id: 13,
    title: `Мельница с раскрытием`,
    titleEn: `Windmill lockout`,
    desc: ``,
    rating: 1,
    elementId: 6,
    createdAt: null,
  },
  {
    id: 14,
    title: `Волна`,
    titleEn: `Reel`,
    desc: ``,
    rating: 1,
    elementId: 7,
    createdAt: null,
  },
  {
    id: 15,
    title: `Волна сверху-снизу`,
    titleEn: `Shoulder to hip reel`,
    desc: ``,
    rating: 1,
    elementId: 7,
    createdAt: null,
  },
  {
    id: 16,
    title: `Пила`,
    titleEn: `Buzzsaw`,
    desc: ``,
    rating: 1,
    elementId: 8,
    createdAt: null,
  },
  {
    id: 17,
    title: `Пила (вариация)`,
    titleEn: `Buzzsaw variation`,
    desc: ``,
    rating: 1,
    elementId: 8,
    createdAt: null,
  },
  {
    id: 18,
    title: `Раскрытия`,
    titleEn: `Lockout`,
    desc: ``,
    rating: 1,
    elementId: 9,
    createdAt: null,
  },
  {
    id: 19,
    title: `Раскрытия из двухбиток/трехбиток и мельницы`,
    titleEn: `Lockout from 2-3-beat weaves/windmill`,
    desc: ``,
    rating: 1,
    elementId: 9,
    createdAt: null,
  },
  {
    id: 20,
    title: `Маятники`,
    titleEn: `Pendulum`,
    desc: ``,
    rating: 1,
    elementId: 10,
    createdAt: null,
  },
  {
    id: 21,
    title: `Связки с маятниками`,
    titleEn: `Pendulum variations`,
    desc: ``,
    rating: 2,
    elementId: 10,
    createdAt: null,
  },
  {
    id: 22,
    title: `Остановки вниз`,
    titleEn: `Stall down`,
    desc: ``,
    rating: 1,
    elementId: 11,
    createdAt: null,
  },
  {
    id: 23,
    title: `Остановки по очереди`,
    titleEn: `Stall in course`,
    desc: ``,
    rating: 1,
    elementId: 11,
    createdAt: null,
  },
  {
    id: 24,
    title: `Последовательные остановки`,
    titleEn: `Stall in course 2`,
    desc: ``,
    rating: 2,
    elementId: 11,
    createdAt: null,
  },
  {
    id: 25,
    title: `Основные остановки`,
    titleEn: `Stall basic`,
    desc: ``,
    rating: 1,
    elementId: 11,
    createdAt: null,
  },
  {
    id: 26,
    title: `8 остановок`,
    titleEn: `8 stall`,
    desc: ``,
    rating: 2,
    elementId: 11,
    createdAt: null,
  },
  {
    id: 27,
    title: `Остановки за головой`,
    titleEn: `Stall behind the back`,
    desc: ``,
    rating: 2,
    elementId: 11,
    createdAt: null,
  },
  {
    id: 28,
    title: `Повороты с остановками`,
    titleEn: `Stall in turns`,
    desc: ``,
    rating: 2,
    elementId: 11,
    createdAt: null,
  },
  {
    id: 29,
    title: `Остановки вверх`,
    titleEn: `Stall up`,
    desc: ``,
    rating: 1,
    elementId: 11,
    createdAt: null,
  },
  {
    id: 30,
    title: `Фонтан`,
    titleEn: `Fountain`,
    desc: ``,
    rating: 2,
    elementId: 12,
    createdAt: null,
  },
  {
    id: 32,
    title: `Штопор`,
    titleEn: `Corkscrew`,
    desc: ``,
    rating: 1,
    elementId: 13,
    createdAt: null,
  },
  {
    id: 35,
    title: `Вращение пои за спиной `,
    titleEn: `BTB spinning`,
    desc: ``,
    rating: 2,
    elementId: 14,
    createdAt: null,
  },
  {
    id: 36,
    title: `Двухбитка и трехбитка за спиной`,
    titleEn: `BTB 2-3-beat weaves`,
    desc: ``,
    rating: 3,
    elementId: 14,
    createdAt: null,
  },
  {
    id: 37,
    title: `Переходы на элементы за спиной`,
    titleEn: `BTB variations`,
    desc: ``,
    rating: 3,
    elementId: 14,
    createdAt: null,
  },
  {
    id: 39,
    title: `Кроссер за спиной`,
    titleEn: `BTB crosser`,
    desc: ``,
    rating: 4,
    elementId: 14,
    createdAt: null,
  },
  {
    id: 40,
    title: `Кроссер`,
    titleEn: `Crosser`,
    desc: ``,
    rating: 3,
    elementId: 15,
    createdAt: null,
  },
  {
    id: 42,
    title: `Космо`,
    titleEn: `Cosmo`,
    desc: ``,
    rating: 3,
    elementId: 16,
    createdAt: null,
  },
  {
    id: 44,
    title: `Изоляция`,
    titleEn: `Isolation`,
    desc: ``,
    rating: 3,
    elementId: 17,
    createdAt: null,
  },
  {
    id: 46,
    title: `Зацепы`,
    titleEn: `Wraps`,
    desc: ``,
    rating: 2,
    elementId: 18,
    createdAt: null,
  },
  {
    id: 47,
    title: `Пятибитка`,
    titleEn: `5-beat weave`,
    desc: `Восьмерка представляет собой последовательное вращение двух пои c перекрещиванием рук.
Эта разновидность восьмерки называется пятибитка.
Название восьмерки зависит от количества прокрутов пои с каждой стороны.

Выполняя эти движения, важно сохранять ровные плоскости вращения пои слева и справа от себя. Обращайте особое внимание на движения кистей.`,
    rating: 2,
    elementId: 4,
    createdAt: null,
  },
  {
    id: 49,
    title: `Спираль`,
    titleEn: `Spiral`,
    desc: ``,
    rating: 3,
    elementId: 20,
    createdAt: null,
  },
  {
    id: 51,
    title: `Бесконечная спираль`,
    titleEn: `Spiral infinity`,
    desc: ``,
    rating: 3,
    elementId: 20,
    createdAt: null,
  },
  {
    id: 52,
    title: `Спираль за головой`,
    titleEn: `Spiral BTB`,
    desc: ``,
    rating: 3,
    elementId: 20,
    createdAt: null,
  },
  {
    id: 53,
    title: `Вращение под ногами`,
    titleEn: `Under the leg`,
    desc: ``,
    rating: 3,
    elementId: 21,
    createdAt: null,
  },
  {
    id: 55,
    title: `Атомик`,
    titleEn: `Atomic`,
    desc: ``,
    rating: 3,
    elementId: 22,
    createdAt: null,
  },
  {
    id: 57,
    title: `Атомик (пятибитка)`,
    titleEn: `5-beat weave atomic`,
    desc: ``,
    rating: 4,
    elementId: 22,
    createdAt: null,
  },
  {
    id: 58,
    title: `Гиперлуп`,
    titleEn: `Hyperloop`,
    desc: ``,
    rating: 3,
    elementId: 23,
    createdAt: null,
  },
  {
    id: 59,
    title: `Эйрврап`,
    titleEn: `Airwrap`,
    desc: ``,
    rating: 2,
    elementId: 23,
    createdAt: null,
  },
  {
    id: 62,
    title: `Спиновый цветок одной рукой`,
    titleEn: `Spin flower by one hand`,
    desc: ``,
    rating: 2,
    elementId: 25,
    createdAt: null,
  },
  {
    id: 63,
    title: `Фронтальные оппозитные спиновые цветки`,
    titleEn: `Wallplane opposite same-time spin flowers`,
    desc: ``,
    rating: 3,
    elementId: 25,
    createdAt: null,
  },
  {
    id: 64,
    title: `Спиновый цветок двумя руками`,
    titleEn: `Spin  flower variation`,
    desc: ``,
    rating: 3,
    elementId: 25,
    createdAt: null,
  },
  {
    id: 66,
    title: `Антиспиновый цветок одной рукой`,
    titleEn: `Antispin flower by one hand`,
    desc: ``,
    rating: 3,
    elementId: 25,
    createdAt: null,
  },
  {
    id: 67,
    title: `Гибрид`,
    titleEn: `Hybrid`,
    desc: ``,
    rating: 3,
    elementId: 26,
    createdAt: null,
  },
  {
    id: 68,
    title: `Спин-антиспиновый гибрид`,
    titleEn: `Spin-antispin hybrid`,
    desc: ``,
    rating: 5,
    elementId: 26,
    createdAt: null,
  },
  {
    id: 70,
    title: `Кэтай`,
    titleEn: `Cateye`,
    desc: ``,
    rating: 4,
    elementId: 27,
    createdAt: null,
  },
  {
    id: 71,
    title: `Горизонтальный кэтай`,
    titleEn: `Horizontal cateye`,
    desc: ``,
    rating: 4,
    elementId: 27,
    createdAt: null,
  },
  {
    id: 73,
    title: `Бриллиант Зана`,
    titleEn: `Zan's diamond`,
    desc: ``,
    rating: 4,
    elementId: 28,
    createdAt: null,
  },
  {
    id: 74,
    title: `3D цветки`,
    titleEn: `3D flowers`,
    desc: ``,
    rating: 3,
    elementId: 29,
    createdAt: null,
  },
  {
    id: 75,
    title: `3D композиции`,
    titleEn: `3D variations`,
    desc: ``,
    rating: 3,
    elementId: 29,
    createdAt: null,
  },
  {
    id: 76,
    title: `Броски 1`,
    titleEn: `Throws 1`,
    desc: ``,
    rating: 3,
    elementId: 30,
    createdAt: null,
  },
  {
    id: 77,
    title: `Броски 2`,
    titleEn: `Throws 2`,
    desc: ``,
    rating: 3,
    elementId: 30,
    createdAt: null,
  },
  {
    id: 78,
    title: `Точки баланса`,
    titleEn: `Balance points`,
    desc: ``,
    rating: 4,
    elementId: 31,
    createdAt: null,
  },
  {
    id: 79,
    title: `Прокаты по внутренней стороне руки`,
    titleEn: `Inner forearm roll`,
    desc: ``,
    rating: 4,
    elementId: 31,
    createdAt: null,
  },
  {
    id: 80,
    title: `Прокаты по внешней стороне руки`,
    titleEn: `Outer forearm roll`,
    desc: ``,
    rating: 4,
    elementId: 31,
    createdAt: null,
  },
  {
    id: 81,
    title: `Хват одной рукой`,
    titleEn: `One-hand grip`,
    desc: ``,
    rating: 3,
    elementId: 32,
    createdAt: null,
  },
  {
    id: 82,
    title: `Двухбитка одной рукой`,
    titleEn: `One-hand 2-beat weave`,
    desc: ``,
    rating: 4,
    elementId: 32,
    createdAt: null,
  },
  {
    id: 83,
    title: `Супермен`,
    titleEn: `Superman weave`,
    desc: ``,
    rating: 4,
    elementId: 32,
    createdAt: null,
  },
  {
    id: 84,
    title: `Супермен с поворотами`,
    titleEn: `Superman turns`,
    desc: ``,
    rating: 4,
    elementId: 32,
    createdAt: null,
  },
  {
    id: 85,
    title: `Фантастическая четверка`,
    titleEn: `Fantastic four weave`,
    desc: ``,
    rating: 4,
    elementId: 32,
    createdAt: null,
  },
  {
    id: 86,
    title: `Стейлы одной рукой`,
    titleEn: `One-hand stall`,
    desc: ``,
    rating: 4,
    elementId: 32,
    createdAt: null,
  },
  {
    id: 87,
    title: `Спираль одной рукой`,
    titleEn: `One-Hand spiral`,
    desc: ``,
    rating: 4,
    elementId: 32,
    createdAt: null,
  },
  {
    id: 88,
    title: `Перехваты пои`,
    titleEn: `3 poi stack-swap framework `,
    desc: ``,
    rating: 5,
    elementId: 33,
    createdAt: null,
  },
  {
    id: 89,
    title: `Супермен с тремя пои`,
    titleEn: `3 poi superman weave`,
    desc: ``,
    rating: 5,
    elementId: 33,
    createdAt: null,
  },
  {
    id: 90,
    title: `Стиль "Стрелок"`,
    titleEn: `Gunslinger style`,
    desc: ``,
    rating: 5,
    elementId: 34,
    createdAt: null,
  },
  {
    id: 91,
    title: `Космические трюки`,
    titleEn: `Keith's Negative space trix`,
    desc: ``,
    rating: 4,
    elementId: 34,
    createdAt: null,
  },
  {
    id: 93,
    title: `Горизонтальный трюк Мела`,
    titleEn: `Mel's horizontal SNES trix`,
    desc: ``,
    rating: 4,
    elementId: 34,
    createdAt: null,
  },
  {
    id: 94,
    title: `Денвер`,
    titleEn: `Denver`,
    desc: ``,
    rating: 4,
    elementId: 35,
    createdAt: null,
  },
  {
    id: 95,
    title: `Смена рук`,
    titleEn: `Hand Switching`,
    desc: ``,
    rating: 4,
    elementId: 35,
    createdAt: null,
  },
  {
    id: 96,
    title: `Трех- и четырехбитные вариации`,
    titleEn: `3-4-beats variations`,
    desc: ``,
    rating: 4,
    elementId: 35,
    createdAt: null,
  },
  {
    id: 97,
    title: `Теория четырех битов`,
    titleEn: `4-beat theory`,
    desc: ``,
    rating: 4,
    elementId: 35,
    createdAt: null,
  },
  {
    id: 98,
    title: `Четырехбитная смена рук`,
    titleEn: `4-beat arm changes`,
    desc: ``,
    rating: 4,
    elementId: 35,
    createdAt: null,
  },
  {
    id: 99,
    title: `Парные вариации`,
    titleEn: `Partner variations`,
    desc: ``,
    rating: 4,
    elementId: 35,
    createdAt: null,
  },
  {
    id: 100,
    title: `Асинхронная волна`,
    titleEn: `Split-time reel`,
    desc: ``,
    rating: 1,
    elementId: 7,
    createdAt: null,
  },
  {
    id: 101,
    title: `Асинхронная волна с поворотом`,
    titleEn: `Shoulder to hip reel turn`,
    desc: ``,
    rating: 2,
    elementId: 7,
    createdAt: null,
  },
  {
    id: 102,
    title: `Крыло`,
    titleEn: `CAP`,
    desc: ``,
    rating: 3,
    elementId: 36,
    createdAt: null,
  },
  {
    id: 103,
    title: `Вействрап`,
    titleEn: `Waistwrap`,
    desc: ``,
    rating: 2,
    elementId: 18,
    createdAt: null,
  },
  {
    id: 104,
    title: `Вействрап за спиной`,
    titleEn: `BTB waistwrap`,
    desc: ``,
    rating: 4,
    elementId: 14,
    createdAt: null,
  },
  {
    id: 105,
    title: `Шагающая бабочка (вперед)`,
    titleEn: `Thread-the-niddle forward`,
    desc: ``,
    rating: 2,
    elementId: 3,
    createdAt: null,
  },
  {
    id: 106,
    title: `Шагающая бабочка (назад)`,
    titleEn: `Thread-the-niddle backward`,
    desc: ``,
    rating: 2,
    elementId: 3,
    createdAt: null,
  },
  {
    id: 108,
    title: `16 остановок`,
    titleEn: `16 stall`,
    desc: ``,
    rating: 3,
    elementId: 11,
    createdAt: null,
  },
  {
    id: 109,
    title: `Трилистник в круге`,
    titleEn: `Triquetra`,
    desc: ``,
    rating: 4,
    elementId: 26,
    createdAt: null,
  },
  {
    id: 110,
    title: `Оппозитный (бабочковый) кроссер`,
    titleEn: `Opposite (butterfly) crosser`,
    desc: ``,
    rating: 3,
    elementId: 15,
    createdAt: `2016-01-10T17:01:57.136Z`,
  },
  {
    id: 112,
    title: `Оппозитный (бабочковый) космо`,
    titleEn: `Opposite (butterfly) cosmo`,
    desc: ``,
    rating: 3,
    elementId: 16,
    createdAt: `2016-01-10T19:14:30.575Z`,
  },
  {
    id: 113,
    title: `Спиральные вариации`,
    titleEn: `Spiral variatons`,
    desc: ``,
    rating: 3,
    elementId: 20,
    createdAt: `2016-01-10T19:36:46.985Z`,
  },
  {
    id: 114,
    title: `Антибрид`,
    titleEn: `Antibrid`,
    desc: ``,
    rating: 3,
    elementId: 26,
    createdAt: `2016-01-10T19:59:31.744Z`,
  },
  {
    id: 115,
    title: `Маятник-магнит`,
    titleEn: `Pendulum magnet`,
    desc: ``,
    rating: 2,
    elementId: 10,
    createdAt: `2016-01-10T20:14:13.468Z`,
  },
  {
    id: 116,
    title: `Оппозитная (бабочковая) волна с поворотом`,
    titleEn: `Opposite (butterfly) reel in turn`,
    desc: ``,
    rating: 2,
    elementId: 7,
    createdAt: `2016-01-10T20:23:19.828Z`,
  },
  {
    id: 117,
    title: `Бабочковые вариации`,
    titleEn: `Butterfly variations`,
    desc: ``,
    rating: 2,
    elementId: 3,
    createdAt: `2016-01-10T20:28:40.510Z`,
  },
  {
    id: 118,
    title: `Раскрытия из оппозитного космо`,
    titleEn: `Opposite cosmo lockouts`,
    desc: ``,
    rating: 3,
    elementId: 16,
    createdAt: `2016-01-10T20:46:46.834Z`,
  },
  {
    id: 119,
    title: `Оппозитный (бабочковый) цветок с поворотом`,
    titleEn: `Opposite (butterfly) flower in turn`,
    desc: ``,
    rating: 3,
    elementId: 25,
    createdAt: `2016-01-10T20:51:51.968Z`,
  },
  {
    id: 120,
    title: `Оппозитный (бабочковый) цветок`,
    titleEn: `Opposite (butterfly) flower`,
    desc: ``,
    rating: 3,
    elementId: 25,
    createdAt: `2016-01-10T20:56:41.684Z`,
  },
  {
    id: 121,
    title: `Гуфи цветок перед собой`,
    titleEn: `Wallplane goofy flower`,
    desc: ``,
    rating: 3,
    elementId: 25,
    createdAt: `2016-01-10T21:04:53.052Z`,
  },
  {
    id: 122,
    title: `Полуфонтан`,
    titleEn: `2-beat fountain`,
    desc: ``,
    rating: 2,
    elementId: 12,
    createdAt: `2016-01-10T21:09:28.914Z`,
  },
  {
    id: 123,
    title: `Горизонтальные остановки`,
    titleEn: `Stall horizontal`,
    desc: ``,
    rating: 2,
    elementId: 11,
    createdAt: `2016-01-10T21:14:27.165Z`,
  },
  {
    id: 124,
    title: `Раскрытия с поворотами`,
    titleEn: `Lockouts in turn`,
    desc: ``,
    rating: 2,
    elementId: 9,
    createdAt: `2016-01-10T21:36:45.505Z`,
  },
  {
    id: 125,
    title: `8-шаговое крыло`,
    titleEn: `8-step CAP`,
    desc: ``,
    rating: 5,
    elementId: 36,
    createdAt: `2016-01-10T22:03:23.776Z`,
  },
  {
    id: 126,
    title: `Антиспиновый кроссер за головой`,
    titleEn: `BTH antispin crosser convertation`,
    desc: ``,
    rating: 5,
    elementId: 34,
    createdAt: `2016-01-10T22:08:03.441Z`,
  },
  {
    id: 127,
    title: `Тоннельные пои`,
    titleEn: `Tonnel poi`,
    desc: ``,
    rating: 5,
    elementId: 37,
    createdAt: `2016-02-03T20:36:16.291Z`,
  },
].sort(u.byPkAsc)
