import * as u from './util.mjs'

export default [
  {
    id: 1,
    fullName: `Иван Mel Горбунов`,
    image: `images/mel.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 2,
    fullName: `Андрей Rikley Филиппов`,
    image: `images/rikley.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 3,
    fullName: `Борис Elros Омелин`,
    image: `images/elros.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 4,
    fullName: `Светлана Clair(e) Ковалева`,
    image: `images/claire.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 5,
    fullName: `Фёдор Firestarter Шарапов`,
    image: `images/firestarter.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 6,
    fullName: `Евгений Next Лобанов`,
    image: `images/next.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 7,
    fullName: `Yuta Imamura`,
    image: `images/yuta.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 8,
    fullName: `Иван Libero Петров`,
    image: `images/9tkbE3lpwFg_0Uj9yUB.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 9,
    fullName: `Митяй Z Замота`,
    image: `images/mityai-zamota.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 10,
    fullName: `Иван Маслов`,
    image: `images/_Jk4yG7xauM.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 11,
    fullName: `Антон Plombir Мальцев`,
    image: `images/Anton_Maltsev.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 12,
    fullName: `Лара Лё`,
    image: `images/Lara_Le.png`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 13,
    fullName: `Антон Кузляев`,
    image: `images/Antonio_Kuzlyaev.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 14,
    fullName: `AquaThane`,
    image: `images/AquaThane.png`,
    youtubeChannelUrl: `https://www.youtube.com/user/AquaThane`,
    url: ``,
  },
  {
    id: 15,
    fullName: `Ben Drex Drexler`,
    image: `images/6398_collage_752.jpg`,
    youtubeChannelUrl: `https://www.youtube.com/user/TaoAvatar20`,
    url: ``,
  },
  {
    id: 16,
    fullName: `Иван Бойко`,
    image: `images/z_154f5992.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 17,
    fullName: `Дмитрий Fess Рабцевич`,
    image: `images/Fess.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 18,
    fullName: `Евгений Пилипенко`,
    image: `images/5umi_M-MhbU.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 19,
    fullName: `Евгений Новиков`,
    image: `images/Novikov.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 20,
    fullName: `Fess & Mrak`,
    image: `images/x_a9af8993.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 21,
    fullName: `Chris Kelly`,
    image: ``,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 22,
    fullName: `Santiago Escobar`,
    image: ``,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 23,
    fullName: `Leo`,
    image: ``,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 24,
    fullName: `Rastaxel`,
    image: ``,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 25,
    fullName: `Cyrille`,
    image: ``,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 26,
    fullName: `Vulcan Tech Blog`,
    image: ``,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 27,
    fullName: `Asaf Mor`,
    image: ``,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 28,
    fullName: `Tim Goddard`,
    image: ``,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 29,
    fullName: `Слава Ukrop Амосов`,
    image: `images/Ccd1YzQufek.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 30,
    fullName: `Андрей Крестьянинов`,
    image: `images/GwLlogrtc2c.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 31,
    fullName: `Александр Нагачевский`,
    image: `images/pGrkdd0LvM8.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
  {
    id: 32,
    fullName: `Эрнест Петрович`,
    image: `images/khwPYxUjLdY.jpg`,
    youtubeChannelUrl: ``,
    url: ``,
  },
].sort(u.byPkAsc)
