import * as u from '../scripts/util.mjs'
import * as s from '../scripts/site.mjs'

export function init() {
  return new u.ListPkDesc(
    new s.PageTechVideo({
      id: 1,
      slug: `mel_shadow`,
      title: `Me & My Shadow`,
      titleEn: `Me & My Shadow`,
      youtubeId: `ZKVW9Rz33tQ`,
      createdAt: new Date(`2016-01-14T14:14:37.935Z`),
      authorId: 1,
    }),
    new s.PageTechVideo({
      id: 2,
      slug: `mel_red_pants`,
      title: `Red  Pants`,
      titleEn: `Red  Pants`,
      youtubeId: `rwEx4FCgxJQ`,
      createdAt: new Date(`2016-01-14T14:18:14.023Z`),
      authorId: 1,
    }),
    new s.PageTechVideo({
      id: 3,
      slug: `digitalnoize`,
      title: `Poi Digital Noize`,
      titleEn: `Poi Digital Noize`,
      youtubeId: `cteRB7OoEgI`,
      createdAt: new Date(`2016-02-03T20:20:33.007Z`),
      authorId: 18,
    }),
    new s.PageTechVideo({
      id: 4,
      slug: `tunnel1`,
      title: `Тоннельные пои 1`,
      titleEn: `Tunnel poi 1`,
      youtubeId: `vTdmSakUYnM`,
      createdAt: new Date(`2016-02-03T20:29:44.656Z`),
      authorId: 20,
    }),
    new s.PageTechVideo({
      id: 5,
      slug: `tunnel2`,
      title: `Тоннельные пои 2`,
      titleEn: `Tonnel po 2`,
      youtubeId: `FPcmDYmP40M`,
      createdAt: new Date(`2016-02-03T20:41:40.853Z`),
      authorId: 20,
    }),
    new s.PageTechVideo({
      id: 6,
      slug: `kerzhenets`,
      title: `Kerzhenets 2015 (Fess poi)`,
      titleEn: `Kerzhenets 2015 (Fess poi)`,
      youtubeId: `IbDHJC0y5tY`,
      createdAt: new Date(`2016-02-03T20:55:11.271Z`),
      authorId: 17,
    }),
    new s.PageTechVideo({
      id: 7,
      slug: `novikovpoi1`,
      title: `Poi tech 1`,
      titleEn: `Poi tech 1`,
      youtubeId: `vhaGNdGynpk`,
      createdAt: new Date(`2016-02-03T20:56:06.031Z`),
      authorId: 19,
    }),
    new s.PageTechVideo({
      id: 8,
      slug: `plombirtech1`,
      title: `plombir poi tech blog`,
      titleEn: `plombir poi tech blog`,
      youtubeId: `_pbHVCe7BIc`,
      createdAt: new Date(`2016-02-03T20:57:30.664Z`),
      authorId: 11,
    }),
    new s.PageTechVideo({
      id: 9,
      slug: `plombirtech2`,
      title: `tech blog №2 plombir`,
      titleEn: `tech blog №2 plombir`,
      youtubeId: `hg5AbVBfBcY`,
      createdAt: new Date(`2016-02-03T20:58:14.307Z`),
      authorId: 11,
    }),
    new s.PageTechVideo({
      id: 10,
      slug: `sloppy`,
      title: `Sloppy, Floppy, Not Clubs`,
      titleEn: ``,
      youtubeId: `QCgbKHkJcYU`,
      createdAt: new Date(`2016-02-06T17:48:16.737Z`),
      authorId: 21,
    }),
    new s.PageTechVideo({
      id: 11,
      slug: `things`,
      title: `20 Things With 5 Strings`,
      titleEn: `20 Things With 5 Strings`,
      youtubeId: `zyh3hadRF_g`,
      createdAt: new Date(`2016-02-06T17:49:13.012Z`),
      authorId: 21,
    }),
    new s.PageTechVideo({
      id: 12,
      slug: `business`,
      title: `Back in Business`,
      titleEn: ``,
      youtubeId: `N3m1gHSIbVo`,
      createdAt: new Date(`2016-02-06T17:56:12.417Z`),
      authorId: 22,
    }),
    new s.PageTechVideo({
      id: 13,
      slug: `evolution`,
      title: `Evolution of Poi`,
      titleEn: `Evolution of Poi`,
      youtubeId: `BFwVMhU7BqA`,
      createdAt: new Date(`2016-02-06T17:58:58.628Z`),
      authorId: 22,
    }),
    new s.PageTechVideo({
      id: 14,
      slug: `edge`,
      title: `On The Edge`,
      titleEn: `On The Edge`,
      youtubeId: `kwzrNhe8vow`,
      createdAt: new Date(`2016-02-06T18:01:51.415Z`),
      authorId: 22,
    }),
    new s.PageTechVideo({
      id: 15,
      slug: `bodytracing`,
      title: `Body Tracing — Component Reels`,
      titleEn: `Body Tracing — Component Reels`,
      youtubeId: `GMy-0_9m-5A`,
      createdAt: new Date(`2016-02-06T18:04:45.745Z`),
      authorId: 23,
    }),
    new s.PageTechVideo({
      id: 16,
      slug: `bodytracing2`,
      title: `Body Tracing`,
      titleEn: `Body Tracing`,
      youtubeId: `xf66Vr8UlsE`,
      createdAt: new Date(`2016-02-06T18:08:24.466Z`),
      authorId: 23,
    }),
    new s.PageTechVideo({
      id: 17,
      slug: `uncharted`,
      title: `Uncharted Poi`,
      titleEn: `Uncharted Poi`,
      youtubeId: `vrAj_xOK5-s`,
      createdAt: new Date(`2016-02-06T18:10:02.838Z`),
      authorId: 23,
    }),
    new s.PageTechVideo({
      id: 18,
      slug: `pointhepark`,
      title: `Poi in the park`,
      titleEn: `Poi in the park`,
      youtubeId: `fUmidbeumy0`,
      createdAt: new Date(`2016-02-06T18:12:18.932Z`),
      authorId: 24,
    }),
    new s.PageTechVideo({
      id: 19,
      slug: `nuskool`,
      title: `nuskool / oldskool ?`,
      titleEn: `nuskool / oldskool ?`,
      youtubeId: `gLUszCgu8F8`,
      createdAt: new Date(`2016-02-06T18:15:37.843Z`),
      authorId: 24,
    }),
    new s.PageTechVideo({
      id: 20,
      slug: `rhum`,
      title: `rhum session`,
      titleEn: `rhum session`,
      youtubeId: `9Wm1lYymBHU`,
      createdAt: new Date(`2016-02-06T18:16:43.640Z`),
      authorId: 24,
    }),
    new s.PageTechVideo({
      id: 21,
      slug: `meltingpoi`,
      title: `Melting Poi`,
      titleEn: `Melting Poi`,
      youtubeId: `MrSyQMRfe7g`,
      createdAt: new Date(`2016-02-06T18:19:49.849Z`),
      authorId: 25,
    }),
    new s.PageTechVideo({
      id: 22,
      slug: `brainstorming`,
      title: `Brainstorming`,
      titleEn: `Brainstorming`,
      youtubeId: `Qju4fTGJyRY`,
      createdAt: new Date(`2016-02-06T18:20:36.881Z`),
      authorId: 25,
    }),
    new s.PageTechVideo({
      id: 23,
      slug: `vulcan1`,
      title: `Vulcan Tech Blog #1`,
      titleEn: `Vulcan Tech Blog #1`,
      youtubeId: `KLZVS32TrqM`,
      createdAt: new Date(`2016-02-06T18:26:53.296Z`),
      authorId: 26,
    }),
    new s.PageTechVideo({
      id: 24,
      slug: `vulcan2`,
      title: `Vulcan Tech Blog #2`,
      titleEn: `Vulcan Tech Blog #2`,
      youtubeId: `-u6NLs3l5s0`,
      createdAt: new Date(`2016-02-06T18:28:26.511Z`),
      authorId: 26,
    }),
    new s.PageTechVideo({
      id: 25,
      slug: `vulcan3`,
      title: `Vulcan Tech Blog #3`,
      titleEn: `Vulcan Tech Blog #3`,
      youtubeId: `K0POTaOhX2s`,
      createdAt: new Date(`2016-02-06T18:28:58.767Z`),
      authorId: 26,
    }),
    new s.PageTechVideo({
      id: 26,
      slug: `vulcan4`,
      title: `Vulcan Tech Blog #4`,
      titleEn: `Vulcan Tech Blog #4`,
      youtubeId: `EweaZ6GDyPU`,
      createdAt: new Date(`2016-02-06T18:29:54.096Z`),
      authorId: 26,
    }),
    new s.PageTechVideo({
      id: 27,
      slug: `techblog1`,
      title: `Tech Blog #1`,
      titleEn: `Tech Blog #1`,
      youtubeId: `MBG-A3_0sGM`,
      createdAt: new Date(`2016-02-06T18:41:01.822Z`),
      authorId: 27,
    }),
    new s.PageTechVideo({
      id: 28,
      slug: `techblog2`,
      title: `Tech Blog #2`,
      titleEn: `Tech Blog #2`,
      youtubeId: `jS4hDsY3rFI`,
      createdAt: new Date(`2016-02-06T18:42:09.056Z`),
      authorId: 27,
    }),
    new s.PageTechVideo({
      id: 29,
      slug: `techblog3`,
      title: `Tech Blog #3`,
      titleEn: `Tech Blog #3`,
      youtubeId: `DjdWTfabCJQ`,
      createdAt: new Date(`2016-02-06T18:42:51.097Z`),
      authorId: 27,
    }),
    new s.PageTechVideo({
      id: 30,
      slug: `techblog4`,
      title: `Tech Blog #4`,
      titleEn: `Tech Blog #4`,
      youtubeId: `K33RYwjvxWM`,
      createdAt: new Date(`2016-02-06T18:44:05.012Z`),
      authorId: 27,
    }),
    new s.PageTechVideo({
      id: 31,
      slug: `techblog5`,
      title: `Tech Blog #5`,
      titleEn: `Tech Blog #5`,
      youtubeId: `nGDNtTXOX8U`,
      createdAt: new Date(`2016-02-06T18:44:52.892Z`),
      authorId: 27,
    }),
    new s.PageTechVideo({
      id: 32,
      slug: `predatorpoi`,
      title: `Predator poi`,
      titleEn: `Predator poi`,
      youtubeId: `VgZNGJ_X3Uo`,
      createdAt: new Date(`2016-02-06T19:05:39.464Z`),
      authorId: 28,
    }),
    new s.PageTechVideo({
      id: 33,
      slug: `firesystem4`,
      title: `FireSystem Tech Poi — 4`,
      titleEn: `FireSystem Tech Poi — 4`,
      youtubeId: `KYuqXlE2nww`,
      createdAt: new Date(`2016-02-06T19:28:50.826Z`),
      authorId: 2,
    }),
    new s.PageTechVideo({
      id: 34,
      slug: `firesystem3`,
      title: `FireSystem Tech Poi — 3`,
      titleEn: `FireSystem Tech Poi — 3`,
      youtubeId: `TWd5Jpvd2nQ`,
      createdAt: new Date(`2016-02-06T19:30:43.594Z`),
      authorId: 2,
    }),
    new s.PageTechVideo({
      id: 35,
      slug: `firesystem2`,
      title: `FireSystem Tech Poi — 2`,
      titleEn: `FireSystem Tech Poi — 2`,
      youtubeId: `u_BZ9PtmdPY`,
      createdAt: new Date(`2016-02-06T19:32:02.199Z`),
      authorId: 2,
    }),
    new s.PageTechVideo({
      id: 36,
      slug: `firesystem1`,
      title: `FireSystem Tech Poi — 1`,
      titleEn: `FireSystem Tech Poi — 1`,
      youtubeId: `AiX8FhiA0Dk`,
      createdAt: new Date(`2016-02-06T19:32:40.020Z`),
      authorId: 2,
    }),
    new s.PageTechVideo({
      id: 37,
      slug: `poicomedy`,
      title: `Poi The Divine Comedy`,
      titleEn: `Poi The Divine Comedy`,
      youtubeId: `i95NZv5RtN8`,
      createdAt: new Date(`2016-02-06T19:52:23.290Z`),
      authorId: 18,
    }),
    new s.PageTechVideo({
      id: 38,
      slug: `pieceheat`,
      title: `Piece Heat`,
      titleEn: `Piece Heat`,
      youtubeId: `l7Lbob2uFs4`,
      createdAt: new Date(`2016-02-06T20:25:10.462Z`),
      authorId: 29,
    }),
    new s.PageTechVideo({
      id: 39,
      slug: `tonnel_poi_3`,
      title: `Тоннельные пои 3`,
      titleEn: `Tonnel poi 3`,
      youtubeId: `e0J4BDxcwsY`,
      createdAt: new Date(`2016-02-14T14:49:29.569Z`),
      authorId: 20,
    }),
    new s.PageTechVideo({
      id: 40,
      slug: `4poi`,
      title: `4 пои | тех блог по двойным метеорам`,
      titleEn: `4 poi | double meteor tech blog`,
      youtubeId: `sirVFVFQA7I`,
      createdAt: new Date(`2016-02-15T18:22:32.593Z`),
      authorId: 31,
    }),
    new s.PageTechVideo({
      id: 41,
      slug: `forestpoi`,
      title: `Лесное пойстерство`,
      titleEn: `Forest poi`,
      youtubeId: `ix5HGeJiEw4`,
      createdAt: new Date(`2016-02-15T18:25:22.586Z`),
      authorId: 17,
    }),
  ).norm()
}
