import * as u from '../scripts/util.mjs'
import * as d from '../scripts/dat.mjs'

export function init() {
  return new u.ListPkAsc(
    new d.Author({
      id: 1,
      fullName: `Иван Mel Горбунов`,
      image: `images/mel.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 2,
      fullName: `Андрей Rikley Филиппов`,
      image: `images/rikley.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 3,
      fullName: `Борис Elros Омелин`,
      image: `images/elros.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 4,
      fullName: `Светлана Clair(e) Ковалева`,
      image: `images/claire.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 5,
      fullName: `Фёдор Firestarter Шарапов`,
      image: `images/firestarter.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 6,
      fullName: `Евгений Next Лобанов`,
      image: `images/next.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 7,
      fullName: `Yuta Imamura`,
      image: `images/yuta.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 8,
      fullName: `Иван Libero Петров`,
      image: `images/9tkbE3lpwFg_0Uj9yUB.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 9,
      fullName: `Митяй Z Замота`,
      image: `images/mityai-zamota.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 10,
      fullName: `Иван Маслов`,
      image: `images/_Jk4yG7xauM.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 11,
      fullName: `Антон Plombir Мальцев`,
      image: `images/Anton_Maltsev.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 12,
      fullName: `Лара Лё`,
      image: `images/Lara_Le.png`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 13,
      fullName: `Антон Кузляев`,
      image: `images/Antonio_Kuzlyaev.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 14,
      fullName: `AquaThane`,
      image: `images/AquaThane.png`,
      youtubeChannelUrl: `https://www.youtube.com/user/AquaThane`,
      url: ``,
    }),
    new d.Author({
      id: 15,
      fullName: `Ben Drex Drexler`,
      image: `images/6398_collage_752.jpg`,
      youtubeChannelUrl: `https://www.youtube.com/user/TaoAvatar20`,
      url: ``,
    }),
    new d.Author({
      id: 16,
      fullName: `Иван Бойко`,
      image: `images/z_154f5992.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 17,
      fullName: `Дмитрий Fess Рабцевич`,
      image: `images/Fess.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 18,
      fullName: `Евгений Пилипенко`,
      image: `images/5umi_M-MhbU.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 19,
      fullName: `Евгений Новиков`,
      image: `images/Novikov.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 20,
      fullName: `Fess & Mrak`,
      image: `images/x_a9af8993.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 21,
      fullName: `Chris Kelly`,
      image: ``,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 22,
      fullName: `Santiago Escobar`,
      image: ``,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 23,
      fullName: `Leo`,
      image: ``,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 24,
      fullName: `Rastaxel`,
      image: ``,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 25,
      fullName: `Cyrille`,
      image: ``,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 26,
      fullName: `Vulcan Tech Blog`,
      image: ``,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 27,
      fullName: `Asaf Mor`,
      image: ``,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 28,
      fullName: `Tim Goddard`,
      image: ``,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 29,
      fullName: `Слава Ukrop Амосов`,
      image: `images/Ccd1YzQufek.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 30,
      fullName: `Андрей Крестьянинов`,
      image: `images/GwLlogrtc2c.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 31,
      fullName: `Александр Нагачевский`,
      image: `images/pGrkdd0LvM8.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
    new d.Author({
      id: 32,
      fullName: `Эрнест Петрович`,
      image: `images/khwPYxUjLdY.jpg`,
      youtubeChannelUrl: ``,
      url: ``,
    }),
  ).norm()
}
