import * as u from '../scripts/util.mjs'
import * as s from '../scripts/site.mjs'

export function init() {
  return new u.ListPkAsc(
    new s.PageLesson({
      id: 1,
      moveId: 1,
      authorId: null,
      authorName: `Илья Атис`,
      authorYoutubeChannelUrl: `https://www.youtube.com/c/ProstoPoi`,
      youtubeId: `S9Wxr4xCxjE`,
      title: `Вращение пои вперед`,
      titleEn: `Spin forward`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 2,
      moveId: 2,
      authorId: null,
      authorName: `Илья Атис`,
      authorYoutubeChannelUrl: `https://www.youtube.com/c/ProstoPoi`,
      youtubeId: `RYrbI0kgR24`,
      title: `Вращение пои назад`,
      titleEn: `Spin backward`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 3,
      moveId: 3,
      authorId: null,
      authorName: `Илья Атис`,
      authorYoutubeChannelUrl: `https://www.youtube.com/c/ProstoPoi`,
      youtubeId: `GGEDoulaOiQ`,
      title: `Диагональ вперед`,
      titleEn: `Diagonal forward`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 4,
      moveId: 4,
      authorId: null,
      authorName: `Илья Атис`,
      authorYoutubeChannelUrl: `https://www.youtube.com/c/ProstoPoi`,
      youtubeId: `ZoewIm56yr8`,
      title: `Диагональ назад`,
      titleEn: `Diagonal backward`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 5,
      moveId: 5,
      authorId: null,
      authorName: `Илья Атис`,
      authorYoutubeChannelUrl: `https://www.youtube.com/c/ProstoPoi`,
      youtubeId: `7MrvEwdfedo`,
      title: `Бабочка вперед`,
      titleEn: `Butterfly forward`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 6,
      moveId: 6,
      authorId: null,
      authorName: `Илья Атис`,
      authorYoutubeChannelUrl: `https://www.youtube.com/c/ProstoPoi`,
      youtubeId: `RGRERz2jMoA`,
      title: `Бабочка назад`,
      titleEn: `Butterfly backward`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 8,
      moveId: 8,
      authorId: null,
      authorName: `Илья Атис`,
      authorYoutubeChannelUrl: `https://www.youtube.com/c/ProstoPoi`,
      youtubeId: `3xGJ9YgtTnM`,
      title: `Двухбитка вперед`,
      titleEn: `2-beat weave forward`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 9,
      moveId: 9,
      authorId: null,
      authorName: `Илья Атис`,
      authorYoutubeChannelUrl: `https://www.youtube.com/c/ProstoPoi`,
      youtubeId: `cXDD9_LsZdU`,
      title: `Двухбитка назад`,
      titleEn: `2-beat weave backward`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 10,
      moveId: 10,
      authorId: null,
      authorName: `Илья Атис`,
      authorYoutubeChannelUrl: `https://www.youtube.com/c/ProstoPoi`,
      youtubeId: `JD44ofWYeVg`,
      title: `Трехбитка вперед`,
      titleEn: `3-beat weave forward`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 11,
      moveId: 11,
      authorId: null,
      authorName: `Илья Атис`,
      authorYoutubeChannelUrl: `https://www.youtube.com/c/ProstoPoi`,
      youtubeId: `T7hvxBjcHdA`,
      title: `Трехбитка назад`,
      titleEn: `3-beat weave backward`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 12,
      moveId: 12,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `EnAHJdh4QIc`,
      title: `Мельница`,
      titleEn: `Windmill`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 13,
      moveId: 13,
      authorId: null,
      authorName: `Иван Либеро`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/krutipoi`,
      youtubeId: `bnuaSe1580M`,
      title: `Мельница с раскрытием`,
      titleEn: `Windmill lockout`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 14,
      moveId: 14,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `BAhmRBaWnUA`,
      title: `Волна`,
      titleEn: `Reel`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 15,
      moveId: 15,
      authorId: null,
      authorName: `Иван Либеро`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/krutipoi`,
      youtubeId: `J41CBymKYiU`,
      title: `Волна сверху-снизу`,
      titleEn: `Shoulder to hip reel`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 16,
      moveId: 16,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `hdlFfs3S9zE`,
      title: `Пила`,
      titleEn: `Buzzsaw`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 17,
      moveId: 17,
      authorId: null,
      authorName: ``,
      authorYoutubeChannelUrl: ``,
      youtubeId: `sBZ0fmN2O6U`,
      title: `Пила (вариация)`,
      titleEn: `Buzzsaw variation`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 18,
      moveId: 18,
      authorId: null,
      authorName: `Иван Либеро`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/krutipoi`,
      youtubeId: `2nHJZHTwimc`,
      title: `Раскрытия`,
      titleEn: `Lockout`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 19,
      moveId: 19,
      authorId: null,
      authorName: `Ник Вулси`,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/meenik`,
      youtubeId: `lRVyKo4d30I`,
      title: `Раскрытия из двухбиток/трехбиток и мельницы`,
      titleEn: `Lockout from 2-3-beat weaves/wimdmill`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 20,
      moveId: 20,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `DemdNiNa4oo`,
      title: `Маятники`,
      titleEn: `Pendulum`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 21,
      moveId: 21,
      authorId: null,
      authorName: `Ник Вулси`,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/meenik`,
      youtubeId: `HYZ9zpMrk04`,
      title: `Маятники (вариация)`,
      titleEn: `Pendulum variations`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 22,
      moveId: 22,
      authorId: null,
      authorName: `Иван Либеро`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/krutipoi`,
      youtubeId: `875zXO3QQ6E`,
      title: `Остановки вниз`,
      titleEn: `Stall down`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 23,
      moveId: 23,
      authorId: null,
      authorName: `Иван Либеро`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/krutipoi`,
      youtubeId: `oR5O0yMwIIA`,
      title: `Остановки по очереди`,
      titleEn: `Stall in course`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 24,
      moveId: 24,
      authorId: null,
      authorName: `Иван Либеро`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/krutipoi`,
      youtubeId: `l84of3wxZuQ`,
      title: `Последовательные остановки`,
      titleEn: `Stall in course 2`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 25,
      moveId: 25,
      authorId: null,
      authorName: `Ник Кан`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/nickcannpoi`,
      youtubeId: `7d3U5PdTbsE`,
      title: `Основные остановки`,
      titleEn: `Stall basic`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 26,
      moveId: 26,
      authorId: null,
      authorName: `Юта Иммамура`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/yuta`,
      youtubeId: `-yTMqSJA0pU`,
      title: `8 остановок`,
      titleEn: `8 stall`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 27,
      moveId: 27,
      authorId: null,
      authorName: `Асаф Мор`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/poiboi07`,
      youtubeId: `mb2hzSldmXY`,
      title: `Остановки за головой`,
      titleEn: `Stall behind the back`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 28,
      moveId: 28,
      authorId: null,
      authorName: `Асаф Мор`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/poiboi07`,
      youtubeId: `tT6zH36AIS4`,
      title: `Повороты с остановками`,
      titleEn: `Stall with turns`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 29,
      moveId: 29,
      authorId: null,
      authorName: `Асаф Мор`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/poiboi07`,
      youtubeId: `hSC2SYJTnn4`,
      title: `Остановки вверх`,
      titleEn: `Stall up`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 30,
      moveId: 30,
      authorId: null,
      authorName: `Иван Либеро`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/krutipoi`,
      youtubeId: `XNrUkabb_dA`,
      title: `Фонтан`,
      titleEn: `Fountain`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 32,
      moveId: 32,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `9fCJ8sn_TNw`,
      title: `Штопор`,
      titleEn: `Corkscrew`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 33,
      moveId: 32,
      authorId: null,
      authorName: `Ник Вулси`,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/meenik`,
      youtubeId: `x1QrSTvO278`,
      title: `Штопор`,
      titleEn: `Corkscrew`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 34,
      moveId: 36,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `Wq0X6gNb0as`,
      title: `Трехбитка за спиной`,
      titleEn: `BTB 3-beat weave `,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 35,
      moveId: 35,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `E0y1o6E444o`,
      title: `Вращение пои за спиной `,
      titleEn: `BTB spinning`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 36,
      moveId: 36,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `VImA0uRXzcA`,
      title: `Двухбитка и трехбитка за спиной`,
      titleEn: `BTB 2-3-beat weaves`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 37,
      moveId: 37,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `sWL7FQ4Rijc`,
      title: `Переходы на элементы за спиной`,
      titleEn: `BTB variations`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 39,
      moveId: 39,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `VeFRpZ4ja00`,
      title: `Кроссер за спиной`,
      titleEn: `BTB crosser`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 40,
      moveId: 40,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `L6w3UC-ciXE`,
      title: `Кроссер`,
      titleEn: `Crosser`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 41,
      moveId: 40,
      authorId: null,
      authorName: `Ник Вулси`,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/meenik`,
      youtubeId: `mrY4TwACjcQ`,
      title: `Кроссер`,
      titleEn: `Crosser`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 42,
      moveId: 42,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `zEq0nyI469Q`,
      title: `Космо`,
      titleEn: ``,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 43,
      moveId: 42,
      authorId: null,
      authorName: `Зан Мур`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Zan00`,
      youtubeId: `j2e8lfcjfbQ`,
      title: `Космо`,
      titleEn: `Cosmo`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 44,
      moveId: 44,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `9ThTrs7XUCs`,
      title: `Изоляция`,
      titleEn: `Isolation`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 45,
      moveId: 44,
      authorId: null,
      authorName: `Ник Вулси`,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/meenik`,
      youtubeId: `q5TfLSMr8QE`,
      title: `Изоляция`,
      titleEn: `Isolation`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 46,
      moveId: 46,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `wLXlYXVP-SA`,
      title: `Зацепы`,
      titleEn: `Wraps`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 47,
      moveId: 47,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `K3yjD5jsyAg`,
      title: `Пятибитка`,
      titleEn: `5-beat weave`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 48,
      moveId: 47,
      authorId: null,
      authorName: `Ник Вулси`,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/meenik`,
      youtubeId: `z9PvtqbU8zQ`,
      title: `Пятибитка`,
      titleEn: `5-beat weave`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 49,
      moveId: 49,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `iAwYypqyb8M`,
      title: `Спираль`,
      titleEn: ``,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 50,
      moveId: 49,
      authorId: null,
      authorName: `Ник Вулси`,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/meenik`,
      youtubeId: `LxuBF2iZuv4`,
      title: `Спираль`,
      titleEn: `Spiral`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 51,
      moveId: 51,
      authorId: null,
      authorName: `Ник Вулси`,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/meenik`,
      youtubeId: `WcDTuV8EQpo`,
      title: `Бесконечная спираль`,
      titleEn: `Spiral infinity`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 52,
      moveId: 52,
      authorId: null,
      authorName: `Ник Вулси`,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/meenik`,
      youtubeId: `gvt49G2X9ys`,
      title: `Спираль за головой`,
      titleEn: `Spiral BTB`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 53,
      moveId: 53,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `zhO4Rv-5Wdo`,
      title: `Вращение под ногами`,
      titleEn: `Under the leg`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 54,
      moveId: 53,
      authorId: null,
      authorName: `Ник Вулси`,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/meenik`,
      youtubeId: `HPo2lVZiqJc`,
      title: `Вращение под ногами`,
      titleEn: `Under the leg`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 55,
      moveId: 55,
      authorId: null,
      authorName: `Ник Кан`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/nickcannpoi`,
      youtubeId: `nFAOTb0FBDI`,
      title: `Атомик`,
      titleEn: ``,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 56,
      moveId: 55,
      authorId: null,
      authorName: `Ник Вулси`,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/meenik`,
      youtubeId: `QsNQBZsYiOQ`,
      title: `Атомик`,
      titleEn: `Atomic`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 57,
      moveId: 57,
      authorId: null,
      authorName: `Ник Кан`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/nickcannpoi`,
      youtubeId: `3sl8pOuEseg`,
      title: `Атомик-пятибитка`,
      titleEn: `5-beat weave atomic`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 58,
      moveId: 58,
      authorId: null,
      authorName: `Ник Вулси`,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/meenik`,
      youtubeId: `PyUPclD5DEk`,
      title: `Гиперлуп`,
      titleEn: `Hyperloop`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 59,
      moveId: 59,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `7MBcb7aCO68`,
      title: `Эйрврап`,
      titleEn: `Airwrap`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 60,
      moveId: 59,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `yyxYujn3TIs`,
      title: `Эйрврап из трехбитки`,
      titleEn: `3-beat weave airwrap`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 61,
      moveId: 59,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `0jNbqOeHDok`,
      title: `Эйрврап (вариация)`,
      titleEn: `Airwrap variations`,
      language: `ru`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 62,
      moveId: 62,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `688BDGtSY9g`,
      title: `Спиновый цветок одной рукой`,
      titleEn: `Spin flower by one hand`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 63,
      moveId: 63,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `OhbHVTWu1f0`,
      title: `Фронтальные оппозитные синхронные спиновые цветки`,
      titleEn: `Wallplane opposite same-time spin flowers`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 64,
      moveId: 64,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `5WHa4mCFLx4`,
      title: `Спиновый цветок двумя руками`,
      titleEn: `Sideplane spin  flower variation`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 65,
      moveId: 63,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `aQG3J58I7uM`,
      title: `Фронтальные оппозитные асинхронные спиновые цветки`,
      titleEn: `Wallplane opposite split-time flowers`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 66,
      moveId: 66,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `Jok37bUE-h4`,
      title: `Антиспиновый цветок одной рукой`,
      titleEn: `Antispin flower by one hand`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 67,
      moveId: 67,
      authorId: null,
      authorName: `Того`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/yuta`,
      youtubeId: `RfdA8PEFh74`,
      title: `Гибрид`,
      titleEn: `Hybrid`,
      language: `jp`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 68,
      moveId: 68,
      authorId: null,
      authorName: `Асаф Мор`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/poiboi07`,
      youtubeId: `7qfp7Lpcx4E`,
      title: `Спин-антиспиновый гибрид`,
      titleEn: `Spin-antispin hybrid`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 69,
      moveId: 67,
      authorId: null,
      authorName: `Ник Вулси`,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/meenik`,
      youtubeId: `Om2UEA3dmRQ`,
      title: `Гибрид`,
      titleEn: `Hybrid`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 70,
      moveId: 70,
      authorId: null,
      authorName: `Ноэл`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/iduali`,
      youtubeId: `qqAasLkmS2g`,
      title: `Кэтай`,
      titleEn: `Cateye`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 71,
      moveId: 71,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `3_NALxkBXq8`,
      title: `Горизонтальный кэтай`,
      titleEn: `Horizontal cateye`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 72,
      moveId: 70,
      authorId: null,
      authorName: `Калейдометрик`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Kaleidometric`,
      youtubeId: `9qQmjKf6d8Y`,
      title: `Кэтай`,
      titleEn: `Cateye`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 73,
      moveId: 73,
      authorId: null,
      authorName: `Зан Мур`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Zan00`,
      youtubeId: `QhWo4cLj184`,
      title: `Бриллиант Зана`,
      titleEn: `Zan's diamond`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 74,
      moveId: 74,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `kbA2XYlnfMM`,
      title: `3D цветки`,
      titleEn: `3D flowers`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 75,
      moveId: 75,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `mrcZpJqljmk`,
      title: `3D композиции`,
      titleEn: `3D variations`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 76,
      moveId: 76,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `C7gplZz1HTM`,
      title: `Броски 1`,
      titleEn: `Throws 1`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 77,
      moveId: 77,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `Qv9cUZW06kc`,
      title: `Броски 2`,
      titleEn: `Throws 2`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 78,
      moveId: 78,
      authorId: null,
      authorName: `Асаф Мор`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/poiboi07`,
      youtubeId: `Lev5fQM4JhU`,
      title: `Точки баланса`,
      titleEn: `Balance points`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 79,
      moveId: 79,
      authorId: null,
      authorName: `Асаф Мор`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/poiboi07`,
      youtubeId: `c9hwoMR7igw`,
      title: `Прокаты по внутренней стороне руки`,
      titleEn: `Inner forearm roll`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 80,
      moveId: 80,
      authorId: null,
      authorName: `Асаф Мор`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/poiboi07`,
      youtubeId: `hqL-yRsleIM`,
      title: `Прокаты по внешней стороне руки`,
      titleEn: `Outer forearm roll`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 81,
      moveId: 81,
      authorId: null,
      authorName: `Тим Годдард`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/00goddard`,
      youtubeId: `VdsVPEchzCg`,
      title: `Хват одной рукой`,
      titleEn: `One-hand grip`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 82,
      moveId: 82,
      authorId: null,
      authorName: `Тим Годдард`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/00goddard`,
      youtubeId: `--mXLXm9MIk`,
      title: `Двухбитка одной рукой`,
      titleEn: `One-hand 2-beat weave`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 83,
      moveId: 83,
      authorId: null,
      authorName: `Тим Годдард`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/00goddard`,
      youtubeId: `kyjpq6YM9KA`,
      title: `Супермен`,
      titleEn: `Superman weave`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 84,
      moveId: 84,
      authorId: null,
      authorName: `Тим Годдард`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/00goddard`,
      youtubeId: `e1UKf4Byhiw`,
      title: `Супермен с поворотами`,
      titleEn: `Superman turns`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 85,
      moveId: 85,
      authorId: null,
      authorName: `Тим Годдард`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/00goddard`,
      youtubeId: `haGdWE1X1uo`,
      title: `Фантастическая четверка`,
      titleEn: `Fantastic four weave`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 86,
      moveId: 86,
      authorId: null,
      authorName: `Тим Годдард`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/00goddard`,
      youtubeId: `9ID4dXvT_UU`,
      title: `Стейлы одной рукой`,
      titleEn: `One-hand stall`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 87,
      moveId: 87,
      authorId: null,
      authorName: `Асаф Мор`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/poiboi07`,
      youtubeId: `z-g353uXmug`,
      title: `Спираль одной рукой`,
      titleEn: `One-hand spiral`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 88,
      moveId: 88,
      authorId: null,
      authorName: `Тим Годдард`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/00goddard`,
      youtubeId: `b_P1ysQ75VE`,
      title: `Перехваты пои`,
      titleEn: `3 poi stack-swap framework `,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 89,
      moveId: 89,
      authorId: null,
      authorName: `Тим Годдард`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/00goddard`,
      youtubeId: `mTnNHMoDQwM`,
      title: `Супермен с тремя пои`,
      titleEn: `3 poi superman weave`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 90,
      moveId: 90,
      authorId: null,
      authorName: `Джонатан Альварес`,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/FlowDaddy92`,
      youtubeId: `YcbKO7r2lbg`,
      title: `Стиль "Стрелок"`,
      titleEn: ``,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 91,
      moveId: 91,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `ST0FSw1z93M`,
      title: `Космические трюки 1`,
      titleEn: `Keith's Negative space trix 1`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 92,
      moveId: 91,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `d9AyOQZb9v4`,
      title: `Космические трюки 2`,
      titleEn: `Keith's Negative space trix`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 93,
      moveId: 93,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `wDv_Ec_-atI`,
      title: `Горизонтальный трюк Мела`,
      titleEn: `Mel's horizontal SNES trix`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 94,
      moveId: 94,
      authorId: null,
      authorName: `Зан и Аврора`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Zan00`,
      youtubeId: `I5t8PgeVRIY`,
      title: `Денвер`,
      titleEn: `Denver`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 95,
      moveId: 95,
      authorId: null,
      authorName: `Зан и Аврора`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Zan00`,
      youtubeId: `n32TadMh-rk`,
      title: `Смена рук`,
      titleEn: `Hand Switching`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 96,
      moveId: 96,
      authorId: null,
      authorName: `Джастин и Кристина`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/JustinChristinaFire`,
      youtubeId: `YJGjZr-5sa4`,
      title: `Трех- и четырехбитные вариации`,
      titleEn: `3-4-beats variations`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 97,
      moveId: 97,
      authorId: null,
      authorName: `Джастин и Кристина`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/JustinChristinaFire`,
      youtubeId: `Uef3kZk_9Eo`,
      title: `Теория четырех битов`,
      titleEn: `4-beat theory`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 98,
      moveId: 98,
      authorId: null,
      authorName: `Джастин и Кристина`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/JustinChristinaFire`,
      youtubeId: `iQyL_o41bo8`,
      title: `Четырехбитная смена рук`,
      titleEn: `4-beat arm changes`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 99,
      moveId: 99,
      authorId: null,
      authorName: `Джастин и Кристина`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/JustinChristinaFire`,
      youtubeId: `aruxi4r-3YQ`,
      title: `Парные вариации`,
      titleEn: `Partner variations`,
      language: `en`,
      createdAt: null,
    }),
    new s.PageLesson({
      id: 100,
      moveId: 100,
      authorId: null,
      authorName: `Иван Либеро`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/krutipoi`,
      youtubeId: `M8Gl5pzDUkE`,
      title: `Асинхронная волна`,
      titleEn: `Split-time reel`,
      language: `ru`,
      createdAt: new Date(`2015-08-31T18:30:43.116Z`),
    }),
    new s.PageLesson({
      id: 101,
      moveId: 101,
      authorId: null,
      authorName: `Иван Либеро`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/krutipoi`,
      youtubeId: `3sJsc9nrfnE`,
      title: `Асинхронная волна с поворотом`,
      titleEn: `Shoulder to hip reels turns`,
      language: `ru`,
      createdAt: new Date(`2015-08-31T18:33:55.569Z`),
    }),
    new s.PageLesson({
      id: 102,
      moveId: 102,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `B-o3E7Ix5uM`,
      title: `Крыло`,
      titleEn: `CAP`,
      language: `en`,
      createdAt: new Date(`2015-08-31T20:44:48.406Z`),
    }),
    new s.PageLesson({
      id: 103,
      moveId: 103,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `sJQB01ZaMLs`,
      title: `Вействрап`,
      titleEn: `Waistwrap`,
      language: `en`,
      createdAt: new Date(`2015-08-31T20:51:02.696Z`),
    }),
    new s.PageLesson({
      id: 104,
      moveId: 104,
      authorId: null,
      authorName: `Дрекс`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `JH6s67j5Ri8`,
      title: `Вействрап за спиной`,
      titleEn: `BTB Waistwrap`,
      language: `en`,
      createdAt: new Date(`2015-08-31T20:53:28.705Z`),
    }),
    new s.PageLesson({
      id: 105,
      moveId: 105,
      authorId: null,
      authorName: `Тим Годдард`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/00goddard`,
      youtubeId: `PRHbcBJKW0U`,
      title: `Шагающая бабочка (вперед)`,
      titleEn: `Thread-the-Niddle forward`,
      language: `en`,
      createdAt: new Date(`2015-08-31T20:57:27.386Z`),
    }),
    new s.PageLesson({
      id: 106,
      moveId: 106,
      authorId: null,
      authorName: `Тим Годдард`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/00goddard`,
      youtubeId: `G8zVhHHKriA`,
      title: `Шагающая бабочка (назад)`,
      titleEn: `Thread-the-Niddle backward`,
      language: `en`,
      createdAt: new Date(`2015-08-31T20:58:37.567Z`),
    }),
    new s.PageLesson({
      id: 108,
      moveId: 108,
      authorId: null,
      authorName: `Юта Иммамура`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/yuta`,
      youtubeId: `RmYUU5O82vs`,
      title: `16 стейлов `,
      titleEn: `16 stall`,
      language: `jp`,
      createdAt: new Date(`2015-08-31T21:04:14.236Z`),
    }),
    new s.PageLesson({
      id: 109,
      moveId: 109,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `eLJxazusXl4`,
      title: `Трилистник в круге`,
      titleEn: `Triquetra`,
      language: `ru`,
      createdAt: new Date(`2015-08-31T21:07:59.933Z`),
    }),
    new s.PageLesson({
      id: 110,
      moveId: 102,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `ez_ZQntS41Q`,
      title: `Крыло`,
      titleEn: `CAP`,
      language: `ru`,
      createdAt: new Date(`2015-08-31T21:11:21.121Z`),
    }),
    new s.PageLesson({
      id: 111,
      moveId: 106,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `XvesHHPQ-RI`,
      title: `Шагающая бабочка (назад)`,
      titleEn: `Thread-the-Niddle backward`,
      language: `ru`,
      createdAt: new Date(`2015-08-31T21:30:02.406Z`),
    }),
    new s.PageLesson({
      id: 112,
      moveId: 105,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `http://www.youtube.com/user/Tikhanovich`,
      youtubeId: `Q0sspcGcmXE`,
      title: `Шагающая бабочка (вперед)`,
      titleEn: `Thread-the-Niddle forward`,
      language: `ru`,
      createdAt: new Date(`2015-08-31T21:30:54.539Z`),
    }),
    new s.PageLesson({
      id: 113,
      moveId: 30,
      authorId: null,
      authorName: `Ник Вулси`,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/meenik`,
      youtubeId: `uJqG-R_OEc0`,
      title: `Фонтан`,
      titleEn: `Fountain`,
      language: `en`,
      createdAt: new Date(`2015-09-14T16:45:36.113Z`),
    }),
    new s.PageLesson({
      id: 114,
      moveId: 110,
      authorId: 14,
      authorName: ``,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/AquaThane`,
      youtubeId: `NOe49oePg_s`,
      title: `Оппозитный (бабочковый) кроссер`,
      titleEn: `Opposite (butterfly) crosser`,
      language: `en`,
      createdAt: new Date(`2016-01-10T18:53:24.248Z`),
    }),
    new s.PageLesson({
      id: 115,
      moveId: 112,
      authorId: null,
      authorName: `Константин Тиханович`,
      authorYoutubeChannelUrl: `https://www.youtube.com/watch?v=tmrtp2GY8WY`,
      youtubeId: `tmrtp2GY8WY`,
      title: `Оппозитный (бабочковый) космо`,
      titleEn: `Opposite (buttefly) cosmo`,
      language: `ru`,
      createdAt: new Date(`2016-01-10T19:19:38.529Z`),
    }),
    new s.PageLesson({
      id: 116,
      moveId: 112,
      authorId: null,
      authorName: `Derek`,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/derekjf85`,
      youtubeId: `nj-unsSDCoE`,
      title: `Оппозитный (бабочковый) космо`,
      titleEn: `Opposite (butterfly) cosmo`,
      language: `en`,
      createdAt: new Date(`2016-01-10T19:22:10.793Z`),
    }),
    new s.PageLesson({
      id: 117,
      moveId: 113,
      authorId: 15,
      authorName: ``,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `FjBYYRpXcQk`,
      title: `Спиральные вариации`,
      titleEn: `Spiral variations`,
      language: `en`,
      createdAt: new Date(`2016-01-10T19:41:41.175Z`),
    }),
    new s.PageLesson({
      id: 118,
      moveId: 20,
      authorId: 15,
      authorName: ``,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/TaoAvatar20`,
      youtubeId: `BX9RWpF_9V8`,
      title: `Маятники`,
      titleEn: `Pendulum`,
      language: `en`,
      createdAt: new Date(`2016-01-10T19:55:31.242Z`),
    }),
    new s.PageLesson({
      id: 119,
      moveId: 114,
      authorId: 8,
      authorName: ``,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/krutipoi`,
      youtubeId: `vKmIOfNDX20`,
      title: `Антибрид`,
      titleEn: `Antibrid`,
      language: `ru`,
      createdAt: new Date(`2016-01-10T20:02:19.165Z`),
    }),
    new s.PageLesson({
      id: 120,
      moveId: 115,
      authorId: 8,
      authorName: ``,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/krutipoi`,
      youtubeId: `4cUD2ywiCXI`,
      title: `Маятник-магнит`,
      titleEn: `Pendulum magnet`,
      language: `ru`,
      createdAt: new Date(`2016-01-10T20:15:19.139Z`),
    }),
    new s.PageLesson({
      id: 121,
      moveId: 116,
      authorId: 8,
      authorName: ``,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/krutipoi`,
      youtubeId: `46yhh8xE15Q`,
      title: `Оппозитная (бабочковая) волна с поворотом`,
      titleEn: `Opposite (butterfly) reel in turn`,
      language: `ru`,
      createdAt: new Date(`2016-01-10T20:25:13.756Z`),
    }),
    new s.PageLesson({
      id: 122,
      moveId: 117,
      authorId: 8,
      authorName: ``,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/krutipoi`,
      youtubeId: `N8UjYQehFq0`,
      title: `Бабочковые вариации`,
      titleEn: `Butterfly variations`,
      language: `ru`,
      createdAt: new Date(`2016-01-10T20:30:01.068Z`),
    }),
    new s.PageLesson({
      id: 123,
      moveId: 118,
      authorId: 8,
      authorName: ``,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/krutipoi`,
      youtubeId: `XTL7d67xHyk`,
      title: `Раскрытия из оппозитного космо`,
      titleEn: `Opposite cosmo lockouts`,
      language: `ru`,
      createdAt: new Date(`2016-01-10T20:32:35.523Z`),
    }),
    new s.PageLesson({
      id: 124,
      moveId: 119,
      authorId: 8,
      authorName: ``,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/krutipoi`,
      youtubeId: `agNjxg25IJQagNjxg25IJQ`,
      title: `Оппозитный (бабочковый) цветок с поворотом`,
      titleEn: `Opposite (butterfly) flower in turn`,
      language: `ru`,
      createdAt: new Date(`2016-01-10T20:54:08.485Z`),
    }),
    new s.PageLesson({
      id: 125,
      moveId: 120,
      authorId: 8,
      authorName: ``,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/krutipoi`,
      youtubeId: `m63SzuD-Cgw`,
      title: `Оппозитный (бабочковый) цветок`,
      titleEn: `Opposite (butterfly) flower`,
      language: `ru`,
      createdAt: new Date(`2016-01-10T20:59:13.889Z`),
    }),
    new s.PageLesson({
      id: 126,
      moveId: 121,
      authorId: 8,
      authorName: ``,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/krutipoi`,
      youtubeId: `pPTPpkSELj0`,
      title: `Гуфи цветок перед собой`,
      titleEn: `Wallplane goofy flower`,
      language: `ru`,
      createdAt: new Date(`2016-01-10T21:06:06.261Z`),
    }),
    new s.PageLesson({
      id: 127,
      moveId: 122,
      authorId: 8,
      authorName: `https://www.youtube.com/user/krutipoi`,
      authorYoutubeChannelUrl: ``,
      youtubeId: `LzS-5EWGRKI`,
      title: `Полуфонтан`,
      titleEn: `2-beat fountain`,
      language: `ru`,
      createdAt: new Date(`2016-01-10T21:10:50.244Z`),
    }),
    new s.PageLesson({
      id: 128,
      moveId: 123,
      authorId: 8,
      authorName: ``,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/krutipoi`,
      youtubeId: `ULEz5iNo3DU`,
      title: `Горизонтальные остановки`,
      titleEn: `Stall horizontal`,
      language: `ru`,
      createdAt: new Date(`2016-01-10T21:15:35.894Z`),
    }),
    new s.PageLesson({
      id: 129,
      moveId: 124,
      authorId: 8,
      authorName: ``,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/krutipoi`,
      youtubeId: `HXP0lnVH98A`,
      title: `Раскрытия с поворотами`,
      titleEn: `Lockouts in turn`,
      language: `ru`,
      createdAt: new Date(`2016-01-10T21:38:44.577Z`),
    }),
    new s.PageLesson({
      id: 130,
      moveId: 125,
      authorId: 1,
      authorName: ``,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/PracticaShop`,
      youtubeId: `EZOh53jcy5M`,
      title: `8-шаговое крыло`,
      titleEn: `8-step CAP`,
      language: `ru`,
      createdAt: new Date(`2016-01-10T22:05:02.719Z`),
    }),
    new s.PageLesson({
      id: 131,
      moveId: 126,
      authorId: 1,
      authorName: ``,
      authorYoutubeChannelUrl: `https://www.youtube.com/user/PracticaShop`,
      youtubeId: `C6nAp82cGvo`,
      title: `Антиспиновый кроссер за головой`,
      titleEn: `BTH antispin crosser convertation`,
      language: `ru`,
      createdAt: new Date(`2016-01-10T22:09:15.374Z`),
    }),
  ).norm()
}
