name: main
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.4.0"

      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.22.0"

      - run: npm i
      - run: npm i -g sass@1.37.5

      - run: make build
        env:
          PROD: true

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_branch: pages
          publish_dir: public
